name: Laravel Test

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, sqlite

      - name: Instalar Composer
        run: composer install --no-progress --prefer-dist

      - name: Copiar archivo .env
        run: cp .env.example .env

      - name: Generar clave de aplicación
        run: php artisan key:generate

      - name: Ejecutar migraciones (opcional)
        run: php artisan migrate --no-interaction --env=testing
        continue-on-error: true

      - name: Ejecutar test
        run: php artisan test
